### PR TITLE
fix travis-ci failure by requiring gcc >= 4.9

### PR DESCRIPTION
**Pull request by leque**

### CODE REVIEW

**Comment by shirok** [comment]
Could you refresh me which part is depending on new C11 features?  Just curious, for I can't recall I made a conscious decision to step beyond C99 (without autoconf-testing).

**Comment by leque** [comment]
Ah, I did not look carefully at why builds failed, but `gc/configure` [did not find `libatomic_ops`](https://travis-ci.org/leque/Gauche/jobs/482451683#L2596) and [the build failed around `gauche/priv/atomicP.h`](https://travis-ci.org/leque/Gauche/jobs/482451683#L2665). Should we fix the `libatomic_ops` check instead?

**Comment by Hamayama** [comment]
GC 8.0 以後の gc_atomic_ops.h を見ると、stdatomic.h を使っておらず、
関数名も古い名前が使われているようです。
https://github.com/ivmai/bdwgc/blob/8076a0c36068828523ab3d18af0af130e1547584/include/private/gc_atomic_ops.h

どうも、GCC 4.8 では、これらを使うことはできるが、
stdatomic.h は存在しないという状況だったようです。
https://stackoverflow.com/questions/20326604/stdatomic-h-in-gcc-4-8

単に更新を忘れているのか、それとも、GCC 4.8 でも atomic の機能を使うために、
あえてそのままにしているのか、分かりませんが。。。

**Comment by shirok** [comment]
I added check of stdatomic.h; if libatomic_ops=none and stdatomic.h doesn't exist, Gauche uses __atomic_* gcc builtins.   I checked that code path works (by artificially #undef-ing HAVE_STDATOMIC_H) but if @leque can check if it works with gcc 4.8 in some time I'll appreciate it.

**Comment by leque** [comment]
I have checked with gcc-4.8.4, but [still failing](https://travis-ci.org/leque/Gauche/jobs/484957296#L2745).

```
In file included from dispatch.c:36:0:
gauche/priv/atomicP.h:41:1: error: unknown type name ‘_Atomic’
 typedef volatile _Atomic ScmAtomicWord ScmAtomicVar;
 ^
```

**Comment by shirok** [comment]
How about with https://github.com/shirok/Gauche/commit/64f66be44521565d264ccebda907e11a633efe36 ?

**Comment by leque** [comment]
Ok, everything goes fine. Thanks!

https://travis-ci.org/leque/Gauche/jobs/485066542
